### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by dimaqq** [vmprof/vmprof-server#1]
Python-3.4
error extract
```html
[25/Jun/2015 12:11:35] "POST /api/user/ HTTP/1.1" 500 106891

<div id="summary">
  <h1>TypeError at /api/user/</h1>
  <pre class="exception_value">Unicode-objects must be encoded before hashing</pre>
  <table class="meta">
```

**Comment by xando** [comment]
We are using python 2.7

**Comment by dimaqq** [comment]
Yeah I figured that.
Perhaps you can put that on pypi?

**Comment by xando** [comment]
Hmm. To be honest I don't know. It's not a real Python app, it will get hard to maintain it in pypi. We are planning to make it more like a online service than a standalone app which happens to be webapp (If that makes any sense) 

But I guess in order to have an answer for the question. For now we won't.
